// src/components/ReadMore/ReadMore.vue
<template>
    <div class="app__projects-pop">
        <div class="modal">
            <div class="modal-content">
                <font-awesome-icon :icon="['fas', 'x']" style="font-size:30" color=black  @click="setClose"/>
                <div class="modal-content-text">
                    <div class="content-name p__title">{{ content.title }}</div>
                    <div class="content-description p__content">{{ content.description }}</div>
                    <div class="content-skill p__content">{{ content.skill }}</div>
                    <div class="modal-link">
                        <svg xmlns="http://www.w3.org/2000/svg" height="1em" style="font-size: 30px;" @click="moveGithub" viewBox="0 0 496 512"><path d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"/></svg>
                    </div>
                    <hr />
                    <div class="content-pages">
                        <div v-for="(page, i) in content.pages" :key="i" class="content-page">
                            <div class="content-page-title p__title">{{ i + 1 }}.{{ page[0] }}</div>
                            <div class="content-page-description p__content">{{ page[1] }}</div>
                        </div>
                    </div>
                    <div class="content-imgs">
                        <img v-for="(img, i) in content.imgUrl" :key="i" :src="img" alt="프로젝트" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>

export default {
    props: {
        content: Object,
        setClose:Function
    },
    methods: {
        moveGithub() {
            window.open(this.content.url, '_blank');
        },
    },

};
</script>

<style src="./ReadMore.css">
</style>

// src/component/ReadMore/ReadMore.jsx
import React from 'react';
import {BsGithub, BsX} from 'react-icons/bs';

import './ReadMore.css';

const ReadMore = (props) => {
    const handleClose=()=>{
        props.setOpen(false);
    }
    const moveGithub=()=>{
        window.open(props.content.url,'_blank');
    }
    return (
        <div className='app__projects-pop'>
            <div className="modal">
                <div className="modal-content">
                    <BsX onClick={handleClose} fontSize={40} color="black"/>
                    <div className='modal-content-text'>
                        <div className='content-name p__title'>{props.content.title}</div>
                        <div className='content-description p__content'>{props.content.description}</div>
                        <div className='content-skill p__content'>{props.content.skill}</div>
                        <div className="modal-link">
                            <BsGithub onClick={moveGithub} fontSize={30} color='grey'/>
                        </div>
                        <hr/>
                        <div className='content-pages'>
                            {props.content.pages.map((page,i)=>(
                                <div className='content-page'>
                                    <div className='content-page-title p__title'>{i+1}.{page[0]}</div>
                                    <div className='content-page-description p__content'>{page[1]}</div>
                                </div>
                            ))}
                        </div>
                        <div className='content-imgs'>
                            {
                                props.content.imgUrl.map((img,i)=>(
                                    <img src={img} alt="프로젝트"/>
                                ))
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ReadMore;
